name: habit_current
description: "Daily flow of habits - Habit Current."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3
  flutter: ^3.38.4

dependencies:
  flutter:
    sdk: flutter
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8
  # State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  equatable: ^2.0.7
  # Navigation
  auto_route: ^11.0.0
  # Settings
  shared_preferences: ^2.5.4
  # Database
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  sqlite3_flutter_libs: ^0.5.41
  # Local Notifications
  flutter_local_notifications: ^19.5.0
  flutter_timezone: ^5.0.1
  timezone: ^0.10.1
  # Permission
  permission_handler: ^12.0.1
  # Device info
  device_info_plus: ^12.3.0
  # Others
  path_provider: ^2.1.5
  path: ^1.9.1
  # Images
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.10.4
  auto_route_generator: ^10.4.0
  flutter_launcher_icons: ^0.14.4
  drift_dev: ^2.30.0
  
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  
  config:
    enable-swift-package-manager: false

  assets:
    - assets/images/light/
    - assets/images/dark/
    - assets/fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
        - asset: assets/fonts/Inter-Italic.ttf
          style: italic

flutter_intl:
  enabled: true
